### ISSUE TITLE
pipemenu's "Install" screen doesn't close

### ISSUE THREAD

**Issue by capn-damo** [BunsenLabs/bunsen-pipemenus#41]
When installing an application from a pipemenu, the command "Hit any key to exit..." does not close the screen.

**Comment by johnraff** [comment]
That's strange.
`read -srn1` at the end of promptInstall() in bunsen-common/bl-include.cfg should return after any input.
I just installed gnome-mplayer from the multimedia-pipemenu and the screen closed after hitting the spacebar.

Are you using version 8.4-1 of bunsen-common? I've just pushed the version to 8.4.1-1 to cover a couple of bugfixes committed in September, but it shouldn't affect that behaviour anyway.

**Comment by capn-damo** [comment]
After update/upgrade on a fresh install on my desktop machine, I still have:

```
$ apt-cache policy bunsen-common
bunsen-common:
  Installed: 8.4-1
  Candidate: 8.4-1
  Version table:
 *** 8.4-1 0
        500 http://pkg.bunsenlabs.org/debian/ bunsen-hydrogen/main amd64 Packages
        100 /var/lib/dpkg/status
```

The `read` command works fine in other situations

I re-ran `bl-welcome` in a terminal and the `fini` screen closed as expected, but an application `Install` screen still doesn't close with a keypress.

**Comment by johnraff** [comment]
That's too weird - as I said, it worked fine for me yesterday, and when I used it in the past.

Could you perhaps try in a terminal 

```
. /usr/lib/bunsen/bunsen-common/bl-include.cfg
set -x
promptInstall 'someapp' 'this installs someapp' leafpad
```

and see what happens at the end? 
(Any package will do, and the first two arguments are only decorative.)

At the end I see:

```
+ say '
someapp has been installed successfully.

Hit any key to exit...'
+ sed 's/^/  /'
+ fold -s -w 76

  someapp has been installed successfully.

  Hit any key to exit...
+ [[ '' = \p\a\u\s\e ]]
+ sleep 0
+ read -srn1
+ return 0
john@bunsen:
```

and get the prompt back.

**Comment by capn-damo** [comment]
That works OK - I get the prompt back.

I tried installing an app using a different terminal set with `update-alternatives`. This time `lxterm` opened, ran the installation, and closed successfully!

Seems that it is a bug when using `terminator`?

**Comment by hhhorb** [comment]
I've installed Audacious at least a couple of times from the RC1 ISO root menus without issues. Terminator bug is a distinct possibility, as I quickly remove Terminator, it is insanely slow to open (1/2 second! :stuck_out_tongue_winking_eye: )

**Comment by capn-damo** [comment]
Strange - tried it on the laptop RC1 install and everything works.

I'll close this, because it it may be something I've done. I'll try a fresh install on the desktop and see what happens _before_ I do any configuration.

**Comment by johnraff** [comment]
It doesn't seem to be a terminator bug either - works OK in my VM anyway.

**Comment by capn-damo** [comment]
Fresh install, no configuration, all works as expected. Must be something I did, which is now impossible to reproduce!
